### ISSUE TITLE
Different versions on NPM and Github releases

### ISSUE THREAD

**Issue by igorshubovych** [graingert/WOW#11]
The latest version on Github releases is 1.3.0
![releases graingert wow 2017-09-21 16-01-38](https://user-images.githubusercontent.com/93907/30697089-7087ed88-9ee6-11e7-9c4c-91276be2bdc4.png)

But the latest version on NPM is 1.2.2
![wow js 2017-09-21 16-03-08](https://user-images.githubusercontent.com/93907/30697102-7d8a2014-9ee6-11e7-8755-7a1833023d37.png)

**Comment by snnwolf** [comment]
@igorshubovych see [matthieua's commit](https://github.com/matthieua/WOW/commit/c944ab749f58d47a7efbdc6b2d170b79c9747741)
