### ISSUE TITLE
wow is not playing once when we hide then show the elements

### ISSUE THREAD

**Issue by roro1993** [graingert/WOW#13]
the page loads and the animation plays and finishes.. expected not to animate again

for a certain reason i need to display none the wrapper of one of the animated elements and show it back on a certain condition..

when i show it back the animation inside this wrapper plays again..

how can i stop this behavior??

how can we for example add a class that stops any attempt of the animation after that the element has already animated..

**Comment by roro1993** [comment]
I found out how to do this 


```
  function afterReveal(e){
    e.addEventListener('animationend', function () {
      $(e).addClass('no-animation');
    });
  }

  var wow = new WOW({
    offset:       100,
    callback: afterReveal
  });
  wow.init();
```

and this class 
```
.no-animation{
  animation: unset;
}
```

**Comment by graingert** [comment]
Have you tried using AOS?
