### ISSUE TITLE
Repeated animations

### ISSUE THREAD

**Issue by NicholasG04** [graingert/WOW#14]
Seems to be an issue on a client website, https://scattervolt.com where the animate.css library loads before the animations with wow.js do. Any fix?

**Comment by graingert** [comment]
Have you tried using AOS.js?

**Comment by NicholasG04** [comment]
No because I don't think it is compatible with the same animate.css libraries and is therefore more complicated to setup.

**Comment by graingert** [comment]
I'm pretty sure it's still compatible with the same animate.css...

**Comment by NicholasG04** [comment]
It’s a separate language. I don’t think you’ve looked at it.


Instead of just adding wow to the classes then adding in data-wow-delay etc if so desired you have to use data-aos:<name> for the animations.
