### ISSUE TITLE
delay between iteration

### ISSUE THREAD

**Issue by nurbol-sarsenbayev** [graingert/WOW#18]
Hi! How can I set delay time between each iteration?

**Comment by graingert** [comment]
You should be able to set various animation preferences with:

https://github.com/graingert/WOW/blob/34712a3deadd7ba24633aa8cf5a97675a1c4b56f/src/WOW.js#L301-L303

Have you tried https://michalsnik.github.io/aos/ instead?

**Comment by graingert** [comment]
@nurbol-sarsenbayev looks like it can't be done, you have to configure your own animation with keyframes: https://css-tricks.com/css-keyframe-animation-delay-iterations/

**Comment by nurbol-sarsenbayev** [comment]
I am using wow.js and animate.css in my project. Can I use own animation with wow.js?

**Comment by graingert** [comment]
> I am using wow.js and animate.css in my project.

I know - have you tried AOS instead?

**Comment by nurbol-sarsenbayev** [comment]
Thank you! I created own animation using keyframes like here https://css-tricks.com/css-keyframe-animation-delay-iterations.
