### ISSUE TITLE
Plugin not working with latest version of animate css 4.1.0

### ISSUE THREAD

**Issue by jbraide** [graingert/WOW#36]
I tried using WOW.js with the latest version 4.1.0 of animate.css from cdn.js and it didn't work, had to revert to an earlier version of animate.css  (3.7.2) as I had used it in an earlier project. 

Just for the sake of future users. 
Love the work you guys put in to get it free for all to Use. 
This is just my little way of saying thank you :)

J.D Braide

**Comment by carlo-13** [comment]
Any updates on this ? I also interested in using the last version of Animate-CSS. Thanks

**Comment by graingert** [comment]
@jbraide @carlo-13 have you tried https://michalsnik.github.io/aos/ ?

**Comment by jbraide** [comment]
Will look into it @graingert

**Comment by carlo-13** [comment]
> @jbraide @carlo-13 have you tried https://michalsnik.github.io/aos/ ?

Hi and thanks for your reply. Can I use AOS with Animate.css, or should I use it on it's own ?

**Comment by graingert** [comment]
@carlo-13 animate.css is optional: https://github.com/michalsnik/aos#integrating-external-css-animation-library-eg-animatecss

**Comment by carlo-13** [comment]
Thank you for your reply!

I've tried with the latest version animate.css v4.1.0, but it doesn't seems to be working.
Is it because the default classes were change in the latest version ? ( I am using "animate__animated animate__flipInX" ).


Below is the code I am using if it can help.

In the header:
```
 <!-- Animates Css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.0/animate.min.css" integrity="sha512-kb1CHTNhoLzinkElTgWn246D6pX22xj8jFNKsDmVwIQo+px7n1yjJUZraVuR/ou6Kmgea4vZXZeUDbqKtXkEMg==" crossorigin="anonymous" />
```


Element to animate:
`<h1 data-aos="animate__flipInX">Text to animate on scroll</h1>`


In the footer:

```
    <!-- AOS JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js" integrity="sha512-A7AYk1fGKX6S2SsHywmPkrnzTZHrgiVT7GcQkLGDe2ev0aWb8zejytzS8wjo7PGEXKqJOrjQ4oORtnimIRZBtw==" crossorigin="anonymous"></script>
    
<script>
	AOS.init({
		useClassNames: true,
		initClassName: false,
		animatedClassName: 'animate__animated',
	});
</script>
```

**Comment by graingert** [comment]
I'm not sure, try the https://gitter.im/michalsnik/aos chat room?
