### ISSUE TITLE
Annoying flickering: Content showed before the animation

### ISSUE THREAD

**Issue by lvca** [graingert/WOW#37]
Hy guys,

I'm having this annoying effect where the div is shown before the animation starts resulting in an annoying effect. Look at this:

![WOW-480](https://user-images.githubusercontent.com/312606/88484653-bbd90600-cf35-11ea-81d3-7ca3f4a444b0.gif)

I'm using the default settings and these are the relevant DOM elements:

```
          <div class="about-image wow fadeInRightBig text-center" data-wow-duration="1s" data-wow-delay="0s"
               style="z-index: 90; filter: drop-shadow(0 0 30px #333);">
            <img...>
          </div>
        
          <div class="text-center wow fadeInUp" data-wow-duration="1.3s" data-wow-delay="0s">
```

is that normal or is there something that goes in conflict? Thanks.

**Comment by DanSnow** [comment]
Try adding `visibility: hidden` to your element style. So it will be hidden at first, then it will be set to `visible` after `wow.js` initialized.

**Comment by graingert** [comment]
@lvca did you try aos animate on scroll? https://michalsnik.github.io/aos/

**Comment by lvca** [comment]
`visibility: hidden;` resolved, I don't know why I didn't think about it... Thanks @DanSnow

**Comment by schroef** [comment]
> @lvca did you try aos animate on scroll? https://michalsnik.github.io/aos/

Thanks for the link! I saw this AOS in the readme. Is this by the same devs? The explanation is a bit vague about this.

**Comment by graingert** [comment]
@schroef no it's just a more modern equivalent
