### ISSUE TITLE
Doubts about License

### ISSUE THREAD

**Issue by sergiosantamaria** [graingert/WOW#9]
Hello @graingert 

First of all I have to say that my knowledge about licenses is practically inexistence.

I have found your code by googling. I have to say that it's works nicely. But reading your readme i look that you "forked" the code from another repository, that repository have a payment license but yours is MIT(Which I think that is free to use)..

How it can be? 

Thanks for your work!
Greetings.

**Comment by graingert** [comment]
This was forked from back when the license was still MIT

**Comment by sergiosantamaria** [comment]
Ohh I suppose that.
Thanks for your work. Have I to mention your MIT license anywhere??

**Comment by graingert** [comment]
Yes this applies to all MIT licenced code that you use. See https://procensus.com/acknowledgements/ for an example
